FROM nginx:1.12

# Packages
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    locales \
    certbot \
&& rm -r /var/lib/apt/lists/*

RUN openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

RUN echo "pt_BR.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

ENV LANG=pt_BR.UTF-8
ENV LANGUAGE=pt_BR:pt
ENV LC_CTYPE="pt_BR.UTF-8"
ENV LC_NUMERIC="pt_BR.UTF-8"
ENV LC_TIME="pt_BR.UTF-8"
ENV LC_COLLATE="pt_BR.UTF-8"
ENV LC_MONETARY="pt_BR.UTF-8"
ENV LC_MESSAGES="pt_BR.UTF-8"
ENV LC_PAPER="pt_BR.UTF-8"
ENV LC_NAME="pt_BR.UTF-8"
ENV LC_ADDRESS="pt_BR.UTF-8"
ENV LC_TELEPHONE="pt_BR.UTF-8"
ENV LC_MEASUREMENT="pt_BR.UTF-8"
ENV LC_IDENTIFICATION="pt_BR.UTF-8"
ENV LC_ALL=pt_BR.UTF-8
