FROM nginx:1.12

# Packages
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    locales \
    certbot \
&& rm -r /var/lib/apt/lists/*

RUN openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

RUN locale-gen pt_BR.UTF-8 pt_br && dpkg-reconfigure locales

ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR:pt
ENV LC_ALL pt_BR.UTF-8